version: "3.8"
services:
  postgres:
    image: itssoumen/postgresql-server
    environment:
      POSTGRES_USER: diploma
      POSTGRES_PASSWORD: 11111111
      TZ: "Europe/Minsk"
      PGTZ: "Europe/Minsk"
    ports:
      - "5432:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://postgres:5432/keycloak"
      KC_DB_USERNAME: diploma
      KC_DB_PASSWORD: 11111111
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
